openapi: "3.0.2"
info:
  title: Delivery events
  version: 1.0.0
  license:
    name: MIT-0
  
paths: {}

components:
  schemas:
    DeliveryCompleted:
      x-amazon-event-source: ecommerce.delivery
      x-amazon-events-detail-type: DeliveryCompleted
      description: Event emitted when an order has been delivered
      allOf:
        - $ref: "../../shared/resources/schemas.yaml#/EventBridgeHeader"
        - type: object
          properties:
            detail:
              type: object
              required:
                - orderId
              properties:
                orderId:
                  type: string
                  format: uuid
                  description: Identifier for the order relative to the package
                  example: b2d0c356-f92b-4629-a87f-786331c2842f
                address:
                  $ref: "../../shared/resources/schemas.yaml#/Address"
            
    DeliveryFailed:
      x-amazon-event-source: ecommerce.delivery
      x-amazon-events-detail-type: DeliveryFailed
      description: |
        Event emitted when the delivery service failed to deliver an order.
      allOf:
        - $ref: "../../shared/resources/schemas.yaml#/EventBridgeHeader"
        - type: object
          properties:
            detail:
              type: object
              required:
                - orderId
              properties:
                orderId:
                  type: string
                  format: uuid
                  description: Identifier for the order relative to the packaging request
                  example: b2d0c356-f92b-4629-a87f-786331c2842f
                address:
                  $ref: "../../shared/resources/schemas.yaml#/Address"