openapi: "3.0.2"
info:
  title: Orders events
  version: 1.0.0
  license:
    name: MIT-0

paths: {}

components:
  schemas:
    OrderCreated:
      x-amazon-events-source: ecommerce.order
      x-amazon-events-detail-type: OrderCreated
      description: Event emitted when an order is created.
      allOf:
        - $ref: "../../shared/resources/schemas.yaml#/EventBridgeHeader"
        - type: object
          properties:
            detail:
              $ref: "../../shared/resources/schemas.yaml#/Order"

    OrderModified:
      x-amazon-events-source: ecommerce.order
      x-amazon-events-detail-type: OrderModified
      description: Event emitted when an order is modified.
      allOf:
        - $ref: "../../shared/resources/schemas.yaml#/EventBridgeHeader"
        - type: object
          properties:
            detail:
              type: object
              properties:
                old:
                  $ref: "../../shared/resources/schemas.yaml#/Order"
                new:
                  $ref: "../../shared/resources/schemas.yaml#/Order"
                changed:
                  type: array
                  description: Array containing field names that were changed
                  items:
                    type: string

    OrderDeleted:
      x-amazon-events-source: ecommerce.order
      x-amazon-events-detail-type: OrderDeleted
      description: Event emitted when an order is deleted.
      allOf:
        - $ref: "../../shared/resources/schemas.yaml#/EventBridgeHeader"
        - type: object
          properties:
            detail:
              $ref: "../../shared/resources/schemas.yaml#/Order"
