openapi: "3.0.2"
info:
  title:
    Fn::Sub: "${AWS::StackName}-api"
  version: 1.0.0
  description: Orders service API definition
  license:
    name: MIT-0
    url: https://github.com/aws/mit-0

paths:
  /backend/{orderId}:
    get:
      description: |
        Retrieve a single order.

        This is a backend operation that requires IAM credentials.
      operationId: backendGetOrder
      parameters:
        - name: orderId
          in: path
          description: Order ID in UUID format
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Order item
          content:
            application/json:
              schema:
                type: object
                properties:
                  order:
                    $ref: "../../shared/resources/schemas.yaml#/Order"
        default:
          description: Something went wrong
          content:
            application/json:
              schema:
                $ref: "../../shared/resources/schemas.yaml#/Message"
      security:
        - AWS_IAM: []
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        type: aws_proxy
        uri:
          Fn::Sub: "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetOrderFunction.Arn}/invocations"


components:
  schemas:
    OrderRequest:
      type: object
      description: Information necessary for creating an order.
      properties:
        products:
          type: array
          items:
            $ref: "../../shared/resources/schemas.yaml#/Product"
        address:
          $ref: "../../shared/resources/schemas.yaml#/Address"
        deliveryPrice:
          type: integer
          minimum: 0
        total:
          type: integer
          minimum: 0
  securitySchemes:
    AWS_IAM:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: awsSigv4