openapi: "3.0.2"
info:
  title:
    Fn::Sub: "${AWS::StackName}-api"
  version: 1.0.0
  description: Delivery Pricing API definition
  license:
    name: MIT-0
    url: https://github.com/aws/mit-0

paths:
  /backend/pricing:
    post:
      description: |
        Pricing calculator for deliveries.

        This takes into account the dimension of the product and the address of delivery.
      operationId: backendPricingDelivery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - products
                - address
              properties:
                products:
                  type: array
                  items:
                    $ref: "../../shared/resources/schemas.yaml#/Product"
                address:
                  $ref: "../../shared/resources/schemas.yaml#/Address"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - price
                properties:
                  price:
                    type: integer
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "../../shared/resources/schemas.yaml#/Message"
      x-amazon-apigateway-auth:
        type: AWS_IAM
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        type: aws_proxy
        uri:
          Fn::Sub: "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PricingFunction.Arn}/invocations"
