version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.8
  pre_build:
    commands:
      - apt-get update -y
      - apt-get install -y jq
      - /usr/bin/env python3.8 -m pip install --upgrade pip
      - make requirements npm-install
  build:
    commands:
      - make tests-e2e

reports:
  staging:
    files:
      - '**/*'
    base-directory: 'reports'